# ✅ Day 8: Numpy Basics

## 📌 What is Numpy?
Numpy is a powerful library for numerical computations. It provides support for arrays, matrices, and high-level mathematical functions.

In [1]:
import numpy as np


# ✅ Creating Numpy Arrays

In [2]:
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

arr2 = np.array([[1,2,3], [4,5,6]])
print("2D Array:\n", arr2)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


# ✅ Array Operations

In [3]:
arr = np.array([10, 20, 30, 40])

print("Addition:", arr + 5)
print("Multiplication:", arr * 2)
print("Square Root:", np.sqrt(arr))


Addition: [15 25 35 45]
Multiplication: [20 40 60 80]
Square Root: [3.16227766 4.47213595 5.47722558 6.32455532]


# ✅ Reshape Array

In [4]:
arr = np.arange(1, 13)
reshaped = arr.reshape(3, 4)
print("Reshaped Array:\n", reshaped)


Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# ✅ Indexing & Slicing



In [5]:
arr = np.array([10, 20, 30, 40, 50])
print("Element at index 2:", arr[2])
print("Slicing from index 1 to 3:", arr[1:4])


Element at index 2: 30
Slicing from index 1 to 3: [20 30 40]


# ✅ Random Numbers



In [7]:
rand_nums = np.random.randint(1, 100, 5)
print("Random Integers:", rand_nums)

Random Integers: [45 28 57 14 18]


# 🎯 Mini Task
Create a 1D array of numbers 1 to 15

Reshape it into 3x5

Multiply all elements by 10




In [8]:
# 1. Create 1D Array of Numbers 1 to 15
import numpy as np

arr = np.arange(1, 16)
print("1D Array (1 to 15):", arr)

print("_________________")

# 2. Reshape it into 3x5
reshaped_arr = arr.reshape(3, 5)
print("Reshaped to 3x5:\n", reshaped_arr)

print("_________________")

#  3. Multiply All Elements by 10
multiplied_arr = reshaped_arr * 10
print("Multiplied by 10:\n", multiplied_arr)


1D Array (1 to 15): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
_________________
Reshaped to 3x5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
_________________
Multiplied by 10:
 [[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]
